/* Generated by tools/generate_lanlan_assets.py. Do not edit.
 *
 * Byte offsets into assets/music/lanlan_sfx_16k.pcm, a 16 kHz signed 16-bit
 * little-endian mono pack. The glue layer feeds one clip at a time.
 */
#pragma once

#include <stddef.h>
#include <stdint.h>

typedef struct {
    const char *name;
    uint32_t offset;
    uint32_t bytes;
} lanlan_sfx_clip_t;

enum {
    LANLAN_SFX_BARK = 0,
    LANLAN_SFX_CHIRP = 1,
    LANLAN_SFX_REMINDER = 2,
    LANLAN_SFX_COUNT
};

extern const lanlan_sfx_clip_t lanlan_sfx_clips[LANLAN_SFX_COUNT];
