/* Generated by tools/generate_lanlan_assets.py. Do not edit. */
#include "lanlan_sfx_data.h"

const lanlan_sfx_clip_t lanlan_sfx_clips[LANLAN_SFX_COUNT] = {
    {"bark", 0u, 8958u},
    {"chirp", 8958u, 15040u},
    {"reminder", 23998u, 14080u},
    {"bark_soft", 38078u, 9600u},
};
