/* Generated by tools/generate_lanlan_assets.py. Do not edit. */
#include "lanlan_sfx_data.h"

const lanlan_sfx_clip_t lanlan_sfx_clips[LANLAN_SFX_COUNT] = {
    {"bark", 0u, 10880u},
    {"chirp", 10880u, 8320u},
    {"reminder", 19200u, 14080u},
};
