/* Generated from main/lanlan/strings.json by tools/generate_lanlan_assets.py.
 * Do not edit: add the string to the JSON and regenerate.
 *
 * These are the fixed user-visible strings of the application. Free caregiver
 * notes come from the server and are deliberately not part of this table. */
#pragma once

#include <stddef.h>

/* Stable string ids, in table order. */
enum {
    LANLAN_STR_APP_PET_NAME,
    LANLAN_STR_PAGES_HOME,
    LANLAN_STR_PAGES_RECORDS,
    LANLAN_STR_PAGES_DETAIL,
    LANLAN_STR_PAGES_COMPANION,
    LANLAN_STR_PAGES_SETTINGS,
    LANLAN_STR_PAGES_REMINDERS,
    LANLAN_STR_PAGES_STATUS,
    LANLAN_STR_HOME_ENTRY_TODAY,
    LANLAN_STR_HOME_ENTRY_RECORDS,
    LANLAN_STR_HOME_ENTRY_COMPANION,
    LANLAN_STR_HOME_ENTRY_SETTINGS,
    LANLAN_STR_HOME_CLOCK_UNTRUSTED,
    LANLAN_STR_RECORDS_EMPTY,
    LANLAN_STR_RECORDS_EMPTY_UNTRUSTED_CLOCK,
    LANLAN_STR_RECORDS_OPEN_DETAIL,
    LANLAN_STR_RECORDS_MORE_ROWS,
    LANLAN_STR_DETAIL_VIEW_COMPACT,
    LANLAN_STR_DETAIL_VIEW_FULL,
    LANLAN_STR_DETAIL_PERFORMER,
    LANLAN_STR_DETAIL_CREATOR,
    LANLAN_STR_DETAIL_DURATION,
    LANLAN_STR_DETAIL_AMOUNT,
    LANLAN_STR_DETAIL_NOTE,
    LANLAN_STR_DETAIL_NO_NOTE,
    LANLAN_STR_DETAIL_REVISED,
    LANLAN_STR_COMPANION_STATE_IDLE,
    LANLAN_STR_COMPANION_STATE_BLINK,
    LANLAN_STR_COMPANION_STATE_HAPPY,
    LANLAN_STR_COMPANION_PET_HINT,
    LANLAN_STR_SETTINGS_ROW_REFRESH,
    LANLAN_STR_SETTINGS_ROW_MUTE,
    LANLAN_STR_SETTINGS_ROW_REMINDER_SOUND,
    LANLAN_STR_SETTINGS_ROW_REMINDER_LIST,
    LANLAN_STR_SETTINGS_ROW_TIMEZONE,
    LANLAN_STR_SETTINGS_ROW_SYNC,
    LANLAN_STR_SETTINGS_ROW_STORAGE,
    LANLAN_STR_SETTINGS_VALUE_ON,
    LANLAN_STR_SETTINGS_VALUE_OFF,
    LANLAN_STR_REMINDERS_EMPTY,
    LANLAN_STR_REMINDERS_DUE,
    LANLAN_STR_REMINDERS_SOUND_OFF,
    LANLAN_STR_REMINDERS_DISABLED,
    LANLAN_STR_REMINDERS_DISMISS_NOTE,
    LANLAN_STR_STATUS_OK,
    LANLAN_STR_STATUS_OFFLINE,
    LANLAN_STR_STATUS_CREDENTIAL_REJECTED,
    LANLAN_STR_STATUS_CACHE_REBUILT,
    LANLAN_STR_STATUS_RETRY_HINT,
    LANLAN_STR_SYNC_NEVER,
    LANLAN_STR_SYNC_JUST_NOW,
    LANLAN_STR_SYNC_MINUTES_AGO,
    LANLAN_STR_SYNC_HOURS_AGO,
    LANLAN_STR_SYNC_AGE_PREFIX,
    LANLAN_STR_SYNC_DETAIL,
    LANLAN_STR_SYNC_CACHE_COUNT,
    LANLAN_STR_SYNC_CURSOR,
    LANLAN_STR_SYNC_RECORDS_UNIT,
    LANLAN_STR_ERRORS_NETWORK,
    LANLAN_STR_ERRORS_SERVER,
    LANLAN_STR_ERRORS_STORAGE,
    LANLAN_STR_ERRORS_CACHE,
    LANLAN_STR_ERRORS_AUDIO,
    LANLAN_STR_CAREGIVERS_HEHE,
    LANLAN_STR_CAREGIVERS_YANGYANG,
    LANLAN_STR_CAREGIVERS_UNKNOWN,
    LANLAN_STR_CATEGORIES_MEAL,
    LANLAN_STR_CATEGORIES_WATER,
    LANLAN_STR_CATEGORIES_CARE,
    LANLAN_STR_CATEGORIES_CLEANING,
    LANLAN_STR_CATEGORIES_WALK,
    LANLAN_STR_CATEGORIES_OTHER,
    LANLAN_STR_SUBITEMS_BATH,
    LANLAN_STR_SUBITEMS_GROOMING,
    LANLAN_STR_SUBITEMS_TEETH,
    LANLAN_STR_SUBITEMS_COMB,
    LANLAN_STR_SUBITEMS_CARE_OTHER,
    LANLAN_STR_SUBITEMS_EAR,
    LANLAN_STR_SUBITEMS_PAW,
    LANLAN_STR_SUBITEMS_PAD,
    LANLAN_STR_SUBITEMS_LITTER,
    LANLAN_STR_SUBITEMS_CLEANING_OTHER,
    LANLAN_STR_CLEANING_PRESETS_EAR,
    LANLAN_STR_CLEANING_PRESETS_PAW,
    LANLAN_STR_CLEANING_PRESETS_PAD,
    LANLAN_STR_CLEANING_PRESETS_LITTER,
    LANLAN_STR_CLEANING_PRESETS_OTHER,
    LANLAN_STR_UNITS_G,
    LANLAN_STR_UNITS_ML,
    LANLAN_STR_UNITS_SCOOP,
    LANLAN_STR_UNITS_CUP,
    LANLAN_STR_UNITS_PIECE,
    LANLAN_STR_UNITS_BAG,
    LANLAN_STR_UNITS_BOWL,
    LANLAN_STR_UNITS_NONE,
    LANLAN_STR_QUANTITY_UNKNOWN,
    LANLAN_STR_QUANTITY_DURATION_MINUTES,
    LANLAN_STR_QUANTITY_DURATION_UNSET,
    LANLAN_STR_QUANTITY_AMOUNT_UNKNOWN,
    LANLAN_STR_QUANTITY_DATE_MONTH_UNIT,
    LANLAN_STR_QUANTITY_DATE_DAY_UNIT,
    LANLAN_STR_COUNT
};

/* Exact UTF-8 literals. Usable in any constant expression, for example a
 * file-scope initializer. */
#define LANLAN_STR_APP_PET_NAME "懒懒"
#define LANLAN_STR_PAGES_HOME "懒懒"
#define LANLAN_STR_PAGES_RECORDS "最近记录"
#define LANLAN_STR_PAGES_DETAIL "记录详情"
#define LANLAN_STR_PAGES_COMPANION "陪伴"
#define LANLAN_STR_PAGES_SETTINGS "设置"
#define LANLAN_STR_PAGES_REMINDERS "提醒"
#define LANLAN_STR_PAGES_STATUS "同步状态"
#define LANLAN_STR_HOME_ENTRY_TODAY "今天"
#define LANLAN_STR_HOME_ENTRY_RECORDS "最近记录"
#define LANLAN_STR_HOME_ENTRY_COMPANION "陪伴"
#define LANLAN_STR_HOME_ENTRY_SETTINGS "设置"
#define LANLAN_STR_HOME_CLOCK_UNTRUSTED "时间还没校准"
#define LANLAN_STR_RECORDS_EMPTY "还没有记录"
#define LANLAN_STR_RECORDS_EMPTY_UNTRUSTED_CLOCK "还没同步，先看看最近的缓存记录"
#define LANLAN_STR_RECORDS_OPEN_DETAIL "查看详情"
#define LANLAN_STR_RECORDS_MORE_ROWS "更多记录"
#define LANLAN_STR_DETAIL_VIEW_COMPACT "简版"
#define LANLAN_STR_DETAIL_VIEW_FULL "完整"
#define LANLAN_STR_DETAIL_PERFORMER "执行人"
#define LANLAN_STR_DETAIL_CREATOR "记录人"
#define LANLAN_STR_DETAIL_DURATION "时长"
#define LANLAN_STR_DETAIL_AMOUNT "数量"
#define LANLAN_STR_DETAIL_NOTE "备注"
#define LANLAN_STR_DETAIL_NO_NOTE "没有备注"
#define LANLAN_STR_DETAIL_REVISED "已修改"
#define LANLAN_STR_COMPANION_STATE_IDLE "发呆"
#define LANLAN_STR_COMPANION_STATE_BLINK "眨眼"
#define LANLAN_STR_COMPANION_STATE_HAPPY "开心"
#define LANLAN_STR_COMPANION_PET_HINT "按 OK 摸摸头"
#define LANLAN_STR_SETTINGS_ROW_REFRESH "立即刷新"
#define LANLAN_STR_SETTINGS_ROW_MUTE "全局静音"
#define LANLAN_STR_SETTINGS_ROW_REMINDER_SOUND "提醒声音"
#define LANLAN_STR_SETTINGS_ROW_REMINDER_LIST "提醒列表"
#define LANLAN_STR_SETTINGS_ROW_TIMEZONE "时区偏移"
#define LANLAN_STR_SETTINGS_ROW_SYNC "同步信息"
#define LANLAN_STR_SETTINGS_ROW_STORAGE "存储状态"
#define LANLAN_STR_SETTINGS_VALUE_ON "开"
#define LANLAN_STR_SETTINGS_VALUE_OFF "关"
#define LANLAN_STR_REMINDERS_EMPTY "还没有提醒"
#define LANLAN_STR_REMINDERS_DUE "该做了"
#define LANLAN_STR_REMINDERS_SOUND_OFF "提醒声音已关"
#define LANLAN_STR_REMINDERS_DISABLED "已关闭"
#define LANLAN_STR_REMINDERS_DISMISS_NOTE "划走或离开页面不算完成，都要在手机上记录"
#define LANLAN_STR_STATUS_OK "连接正常"
#define LANLAN_STR_STATUS_OFFLINE "离线，正在重试"
#define LANLAN_STR_STATUS_CREDENTIAL_REJECTED "凭证已失效，请重新配置"
#define LANLAN_STR_STATUS_CACHE_REBUILT "缓存已重建，正在重新同步"
#define LANLAN_STR_STATUS_RETRY_HINT "按 OK 重试同步"
#define LANLAN_STR_SYNC_NEVER "还没同步"
#define LANLAN_STR_SYNC_JUST_NOW "刚刚同步"
#define LANLAN_STR_SYNC_MINUTES_AGO "分钟前"
#define LANLAN_STR_SYNC_HOURS_AGO "小时前"
#define LANLAN_STR_SYNC_AGE_PREFIX "数据"
#define LANLAN_STR_SYNC_DETAIL "上次同步"
#define LANLAN_STR_SYNC_CACHE_COUNT "缓存"
#define LANLAN_STR_SYNC_CURSOR "位置"
#define LANLAN_STR_SYNC_RECORDS_UNIT "条"
#define LANLAN_STR_ERRORS_NETWORK "网络不可用"
#define LANLAN_STR_ERRORS_SERVER "服务暂时不可用"
#define LANLAN_STR_ERRORS_STORAGE "存储写入失败"
#define LANLAN_STR_ERRORS_CACHE "缓存读取失败，已重建"
#define LANLAN_STR_ERRORS_AUDIO "声音播放失败"
#define LANLAN_STR_CAREGIVERS_HEHE "赫赫"
#define LANLAN_STR_CAREGIVERS_YANGYANG "羊羊"
#define LANLAN_STR_CAREGIVERS_UNKNOWN "未知"
#define LANLAN_STR_CATEGORIES_MEAL "喂食"
#define LANLAN_STR_CATEGORIES_WATER "喝水"
#define LANLAN_STR_CATEGORIES_CARE "护理"
#define LANLAN_STR_CATEGORIES_CLEANING "清洁"
#define LANLAN_STR_CATEGORIES_WALK "遛狗"
#define LANLAN_STR_CATEGORIES_OTHER "其他"
#define LANLAN_STR_SUBITEMS_BATH "洗澡"
#define LANLAN_STR_SUBITEMS_GROOMING "梳毛"
#define LANLAN_STR_SUBITEMS_TEETH "刷牙"
#define LANLAN_STR_SUBITEMS_COMB "整理毛发"
#define LANLAN_STR_SUBITEMS_CARE_OTHER "其他"
#define LANLAN_STR_SUBITEMS_EAR "掏耳朵"
#define LANLAN_STR_SUBITEMS_PAW "剪指甲"
#define LANLAN_STR_SUBITEMS_PAD "擦脚垫"
#define LANLAN_STR_SUBITEMS_LITTER "清猫砂"
#define LANLAN_STR_SUBITEMS_CLEANING_OTHER "其他"
#define LANLAN_STR_CLEANING_PRESETS_EAR "掏耳朵"
#define LANLAN_STR_CLEANING_PRESETS_PAW "剪指甲"
#define LANLAN_STR_CLEANING_PRESETS_PAD "擦脚垫"
#define LANLAN_STR_CLEANING_PRESETS_LITTER "清猫砂"
#define LANLAN_STR_CLEANING_PRESETS_OTHER "其它清洁"
#define LANLAN_STR_UNITS_G "克"
#define LANLAN_STR_UNITS_ML "毫升"
#define LANLAN_STR_UNITS_SCOOP "勺"
#define LANLAN_STR_UNITS_CUP "杯"
#define LANLAN_STR_UNITS_PIECE "块"
#define LANLAN_STR_UNITS_BAG "袋"
#define LANLAN_STR_UNITS_BOWL "碗"
#define LANLAN_STR_UNITS_NONE ""
#define LANLAN_STR_QUANTITY_UNKNOWN "未知"
#define LANLAN_STR_QUANTITY_DURATION_MINUTES "分钟"
#define LANLAN_STR_QUANTITY_DURATION_UNSET ""
#define LANLAN_STR_QUANTITY_AMOUNT_UNKNOWN "未记录数量"
#define LANLAN_STR_QUANTITY_DATE_MONTH_UNIT "月"
#define LANLAN_STR_QUANTITY_DATE_DAY_UNIT "日"

/* Look up the same literal by id at runtime. */
#define LANLAN_TXT(id) (lanlan_strings[(id)])

/* Index -> exact UTF-8 literal, for table-driven tests and diagnostics. */
extern const char *const lanlan_strings[LANLAN_STR_COUNT];
/* Group name of each string, for diagnostics and the font coverage test. */
extern const char *const lanlan_string_groups[LANLAN_STR_COUNT];
extern const char *const lanlan_string_keys[LANLAN_STR_COUNT];
